export type Constituent = {
  symbol: string;
  name: string;
  weight: number; // approximate index weight %
  sector: string;
};

export const SP500: Constituent[] = [
  { symbol: "AAPL",  name: "Apple",              weight: 7.0,  sector: "Technology" },
  { symbol: "MSFT",  name: "Microsoft",          weight: 6.5,  sector: "Technology" },
  { symbol: "NVDA",  name: "Nvidia",             weight: 6.0,  sector: "Technology" },
  { symbol: "AMZN",  name: "Amazon",             weight: 3.8,  sector: "Cons. Disc." },
  { symbol: "META",  name: "Meta",               weight: 2.5,  sector: "Technology" },
  { symbol: "GOOGL", name: "Alphabet A",         weight: 2.0,  sector: "Technology" },
  { symbol: "GOOG",  name: "Alphabet C",         weight: 1.8,  sector: "Technology" },
  { symbol: "BRK-B", name: "Berkshire",          weight: 1.8,  sector: "Financials" },
  { symbol: "LLY",   name: "Eli Lilly",          weight: 1.5,  sector: "Healthcare" },
  { symbol: "AVGO",  name: "Broadcom",           weight: 1.4,  sector: "Technology" },
  { symbol: "JPM",   name: "JPMorgan",           weight: 1.4,  sector: "Financials" },
  { symbol: "TSLA",  name: "Tesla",              weight: 1.3,  sector: "Cons. Disc." },
  { symbol: "UNH",   name: "UnitedHealth",       weight: 1.2,  sector: "Healthcare" },
  { symbol: "V",     name: "Visa",               weight: 1.1,  sector: "Financials" },
  { symbol: "XOM",   name: "ExxonMobil",         weight: 1.0,  sector: "Energy" },
  { symbol: "COST",  name: "Costco",             weight: 0.9,  sector: "Cons. Staples" },
  { symbol: "MA",    name: "Mastercard",         weight: 0.9,  sector: "Financials" },
  { symbol: "WMT",   name: "Walmart",            weight: 0.8,  sector: "Cons. Staples" },
  { symbol: "HD",    name: "Home Depot",         weight: 0.8,  sector: "Cons. Disc." },
  { symbol: "PG",    name: "P&G",               weight: 0.7,  sector: "Cons. Staples" },
  { symbol: "NFLX",  name: "Netflix",            weight: 0.7,  sector: "Technology" },
  { symbol: "JNJ",   name: "Johnson & Johnson",  weight: 0.7,  sector: "Healthcare" },
  { symbol: "CRM",   name: "Salesforce",         weight: 0.6,  sector: "Technology" },
  { symbol: "ORCL",  name: "Oracle",             weight: 0.6,  sector: "Technology" },
  { symbol: "BAC",   name: "Bank of America",    weight: 0.6,  sector: "Financials" },
  { symbol: "AMD",   name: "AMD",                weight: 0.5,  sector: "Technology" },
  { symbol: "KO",    name: "Coca-Cola",          weight: 0.5,  sector: "Cons. Staples" },
  { symbol: "PEP",   name: "PepsiCo",            weight: 0.5,  sector: "Cons. Staples" },
  { symbol: "MRK",   name: "Merck",              weight: 0.5,  sector: "Healthcare" },
  { symbol: "TMO",   name: "Thermo Fisher",      weight: 0.5,  sector: "Healthcare" },
  { symbol: "CSCO",  name: "Cisco",              weight: 0.5,  sector: "Technology" },
  { symbol: "ABT",   name: "Abbott",             weight: 0.4,  sector: "Healthcare" },
  { symbol: "GE",    name: "GE Aerospace",       weight: 0.4,  sector: "Industrials" },
  { symbol: "ADBE",  name: "Adobe",              weight: 0.4,  sector: "Technology" },
  { symbol: "INTU",  name: "Intuit",             weight: 0.4,  sector: "Technology" },
  { symbol: "TXN",   name: "Texas Instruments",  weight: 0.4,  sector: "Technology" },
  { symbol: "QCOM",  name: "Qualcomm",           weight: 0.4,  sector: "Technology" },
  { symbol: "AMGN",  name: "Amgen",              weight: 0.4,  sector: "Healthcare" },
  { symbol: "MS",    name: "Morgan Stanley",     weight: 0.4,  sector: "Financials" },
  { symbol: "GS",    name: "Goldman Sachs",      weight: 0.4,  sector: "Financials" },
  { symbol: "SPGI",  name: "S&P Global",         weight: 0.4,  sector: "Financials" },
  { symbol: "HON",   name: "Honeywell",          weight: 0.4,  sector: "Industrials" },
  { symbol: "NOW",   name: "ServiceNow",         weight: 0.4,  sector: "Technology" },
  { symbol: "RTX",   name: "RTX Corp",           weight: 0.3,  sector: "Industrials" },
  { symbol: "CAT",   name: "Caterpillar",        weight: 0.3,  sector: "Industrials" },
  { symbol: "NEE",   name: "NextEra Energy",     weight: 0.3,  sector: "Utilities" },
  { symbol: "BKNG",  name: "Booking Holdings",   weight: 0.3,  sector: "Cons. Disc." },
  { symbol: "LIN",   name: "Linde",              weight: 0.3,  sector: "Materials" },
  { symbol: "MU",    name: "Micron",             weight: 0.3,  sector: "Technology" },
  { symbol: "UBER",  name: "Uber",               weight: 0.3,  sector: "Industrials" },
  { symbol: "ISRG",  name: "Intuitive Surgical", weight: 0.3,  sector: "Healthcare" },
  { symbol: "ETN",   name: "Eaton",              weight: 0.3,  sector: "Industrials" },
  { symbol: "IBM",   name: "IBM",                weight: 0.3,  sector: "Technology" },
  { symbol: "AXP",   name: "American Express",   weight: 0.3,  sector: "Financials" },
  { symbol: "LOW",   name: "Lowe's",            weight: 0.3,  sector: "Cons. Disc." },
  { symbol: "PANW",  name: "Palo Alto Networks", weight: 0.3,  sector: "Technology" },
  { symbol: "C",     name: "Citigroup",          weight: 0.2,  sector: "Financials" },
  { symbol: "DE",    name: "Deere & Co",         weight: 0.2,  sector: "Industrials" },
];

export const NASDAQ100: Constituent[] = [
  { symbol: "MSFT",  name: "Microsoft",          weight: 8.9,  sector: "Technology" },
  { symbol: "AAPL",  name: "Apple",              weight: 8.5,  sector: "Technology" },
  { symbol: "NVDA",  name: "Nvidia",             weight: 8.0,  sector: "Technology" },
  { symbol: "AMZN",  name: "Amazon",             weight: 5.2,  sector: "Cons. Disc." },
  { symbol: "META",  name: "Meta",               weight: 3.5,  sector: "Technology" },
  { symbol: "TSLA",  name: "Tesla",              weight: 3.0,  sector: "Cons. Disc." },
  { symbol: "GOOGL", name: "Alphabet A",         weight: 2.5,  sector: "Technology" },
  { symbol: "GOOG",  name: "Alphabet C",         weight: 2.3,  sector: "Technology" },
  { symbol: "AVGO",  name: "Broadcom",           weight: 2.0,  sector: "Technology" },
  { symbol: "COST",  name: "Costco",             weight: 2.0,  sector: "Cons. Staples" },
  { symbol: "NFLX",  name: "Netflix",            weight: 1.8,  sector: "Technology" },
  { symbol: "ASML",  name: "ASML",               weight: 1.5,  sector: "Technology" },
  { symbol: "AMD",   name: "AMD",                weight: 1.3,  sector: "Technology" },
  { symbol: "ADBE",  name: "Adobe",              weight: 1.2,  sector: "Technology" },
  { symbol: "QCOM",  name: "Qualcomm",           weight: 1.2,  sector: "Technology" },
  { symbol: "INTU",  name: "Intuit",             weight: 1.2,  sector: "Technology" },
  { symbol: "CSCO",  name: "Cisco",              weight: 1.1,  sector: "Technology" },
  { symbol: "TXN",   name: "Texas Instruments",  weight: 1.1,  sector: "Technology" },
  { symbol: "PANW",  name: "Palo Alto Networks", weight: 0.9,  sector: "Technology" },
  { symbol: "AMAT",  name: "Applied Materials",  weight: 0.9,  sector: "Technology" },
  { symbol: "MU",    name: "Micron",             weight: 0.9,  sector: "Technology" },
  { symbol: "ADI",   name: "Analog Devices",     weight: 0.8,  sector: "Technology" },
  { symbol: "LRCX",  name: "Lam Research",       weight: 0.8,  sector: "Technology" },
  { symbol: "SNPS",  name: "Synopsys",           weight: 0.7,  sector: "Technology" },
  { symbol: "CDNS",  name: "Cadence Design",     weight: 0.7,  sector: "Technology" },
  { symbol: "KLAC",  name: "KLA Corp",           weight: 0.7,  sector: "Technology" },
  { symbol: "MRVL",  name: "Marvell Tech",       weight: 0.7,  sector: "Technology" },
  { symbol: "INTC",  name: "Intel",              weight: 0.7,  sector: "Technology" },
  { symbol: "CRWD",  name: "CrowdStrike",        weight: 0.7,  sector: "Technology" },
  { symbol: "MELI",  name: "MercadoLibre",       weight: 0.7,  sector: "Cons. Disc." },
  { symbol: "ISRG",  name: "Intuitive Surgical", weight: 0.7,  sector: "Healthcare" },
  { symbol: "REGN",  name: "Regeneron",          weight: 0.6,  sector: "Healthcare" },
  { symbol: "AZN",   name: "AstraZeneca",        weight: 0.6,  sector: "Healthcare" },
  { symbol: "ABNB",  name: "Airbnb",             weight: 0.5,  sector: "Cons. Disc." },
  { symbol: "TTD",   name: "The Trade Desk",     weight: 0.5,  sector: "Technology" },
  { symbol: "DXCM",  name: "Dexcom",             weight: 0.4,  sector: "Healthcare" },
  { symbol: "GEHC",  name: "GE Healthcare",      weight: 0.4,  sector: "Healthcare" },
  { symbol: "FTNT",  name: "Fortinet",           weight: 0.4,  sector: "Technology" },
  { symbol: "ON",    name: "ON Semiconductor",   weight: 0.4,  sector: "Technology" },
  { symbol: "CTAS",  name: "Cintas",             weight: 0.4,  sector: "Industrials" },
  { symbol: "KDP",   name: "Keurig Dr Pepper",   weight: 0.3,  sector: "Cons. Staples" },
  { symbol: "IDXX",  name: "IDEXX Labs",         weight: 0.3,  sector: "Healthcare" },
  { symbol: "VRSK",  name: "Verisk Analytics",   weight: 0.3,  sector: "Industrials" },
  { symbol: "BKR",   name: "Baker Hughes",       weight: 0.3,  sector: "Energy" },
  { symbol: "EA",    name: "Electronic Arts",    weight: 0.3,  sector: "Technology" },
  { symbol: "ZS",    name: "Zscaler",            weight: 0.3,  sector: "Technology" },
  { symbol: "FAST",  name: "Fastenal",           weight: 0.3,  sector: "Industrials" },
  { symbol: "CPRT",  name: "Copart",             weight: 0.3,  sector: "Industrials" },
  { symbol: "EXC",   name: "Exelon",             weight: 0.2,  sector: "Utilities" },
  { symbol: "PCAR",  name: "PACCAR",             weight: 0.2,  sector: "Industrials" },
];

export const DOW30: Constituent[] = [
  { symbol: "UNH",  name: "UnitedHealth",       weight: 10.2, sector: "Healthcare" },
  { symbol: "MSFT", name: "Microsoft",          weight: 5.8,  sector: "Technology" },
  { symbol: "GS",   name: "Goldman Sachs",      weight: 5.7,  sector: "Financials" },
  { symbol: "HD",   name: "Home Depot",         weight: 5.2,  sector: "Cons. Disc." },
  { symbol: "AMGN", name: "Amgen",              weight: 5.0,  sector: "Healthcare" },
  { symbol: "CAT",  name: "Caterpillar",        weight: 4.9,  sector: "Industrials" },
  { symbol: "MCD",  name: "McDonald's",        weight: 4.7,  sector: "Cons. Disc." },
  { symbol: "V",    name: "Visa",               weight: 4.5,  sector: "Financials" },
  { symbol: "CRM",  name: "Salesforce",         weight: 4.5,  sector: "Technology" },
  { symbol: "AXP",  name: "American Express",   weight: 4.3,  sector: "Financials" },
  { symbol: "TRV",  name: "Travelers",          weight: 3.8,  sector: "Financials" },
  { symbol: "BA",   name: "Boeing",             weight: 3.5,  sector: "Industrials" },
  { symbol: "HON",  name: "Honeywell",          weight: 3.3,  sector: "Industrials" },
  { symbol: "IBM",  name: "IBM",                weight: 3.2,  sector: "Technology" },
  { symbol: "AAPL", name: "Apple",              weight: 3.0,  sector: "Technology" },
  { symbol: "MMM",  name: "3M",                 weight: 2.8,  sector: "Industrials" },
  { symbol: "JNJ",  name: "Johnson & Johnson",  weight: 2.7,  sector: "Healthcare" },
  { symbol: "JPM",  name: "JPMorgan Chase",     weight: 2.7,  sector: "Financials" },
  { symbol: "SHW",  name: "Sherwin-Williams",   weight: 2.6,  sector: "Materials" },
  { symbol: "CVX",  name: "Chevron",            weight: 2.6,  sector: "Energy" },
  { symbol: "MRK",  name: "Merck",              weight: 2.5,  sector: "Healthcare" },
  { symbol: "WMT",  name: "Walmart",            weight: 2.4,  sector: "Cons. Staples" },
  { symbol: "PG",   name: "P&G",               weight: 2.3,  sector: "Cons. Staples" },
  { symbol: "NKE",  name: "Nike",               weight: 1.9,  sector: "Cons. Disc." },
  { symbol: "DIS",  name: "Disney",             weight: 1.8,  sector: "Technology" },
  { symbol: "KO",   name: "Coca-Cola",          weight: 1.7,  sector: "Cons. Staples" },
  { symbol: "CSCO", name: "Cisco",              weight: 1.4,  sector: "Technology" },
  { symbol: "DOW",  name: "Dow Inc.",           weight: 1.2,  sector: "Materials" },
  { symbol: "INTC", name: "Intel",              weight: 0.9,  sector: "Technology" },
  { symbol: "VZ",   name: "Verizon",            weight: 0.9,  sector: "Telecom" },
];

export type IndexKey = "sp500" | "nasdaq100" | "dow30";

export const INDEX_META: Record<IndexKey, { label: string; constituents: Constituent[] }> = {
  sp500:    { label: "S&P 500",    constituents: SP500 },
  nasdaq100: { label: "Nasdaq 100", constituents: NASDAQ100 },
  dow30:    { label: "Dow 30",     constituents: DOW30 },
};
