import type { Achievement } from "../types";

export const AI_ACHIEVEMENTS: ReadonlyArray<Achievement> = [
  {
    id: "first_prompt",
    title: "First Prompt",
    description: "Send your first AI query.",
    flavorText: "The model is listening.",
    category: "ai",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.5,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "ai_query_sent", target: 1 },
  },
  {
    id: "power_user",
    title: "Power User",
    description: "Send 10 AI queries.",
    flavorText: "You've learned to ask the right questions.",
    category: "ai",
    tier: "silver",
    points: 25,
    rarityTarget: 0.25,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "ai_query_sent", target: 10 },
  },
  {
    id: "ai_native",
    title: "AI Native",
    description: "Send 50 AI queries.",
    flavorText: "The model and you, co-portfolio managers.",
    category: "ai",
    tier: "gold",
    points: 75,
    rarityTarget: 0.08,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "ai_query_sent", target: 50 },
  },
  {
    id: "screen_wizard",
    title: "Screen Wizard",
    description: "Build a stock screen using AI.",
    flavorText: "You taught the model to filter the noise.",
    category: "ai",
    tier: "silver",
    points: 25,
    rarityTarget: 0.15,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "ai_screen_built", target: 1 },
  },
  {
    id: "fact_checker",
    title: "Fact Checker",
    description: "View an AI-generated Pro/Con analysis.",
    flavorText: "Both sides of the trade, laid bare.",
    category: "ai",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.35,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "ai_pro_con_viewed", target: 1 },
  },
];
