import type { Achievement } from "../types";

export const GOALS: ReadonlyArray<Achievement> = [
  {
    id: "goal_setter",
    title: "Goal Setter",
    description: "Create your first financial goal.",
    flavorText: "A target without a deadline is just a wish.",
    category: "goals",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.45,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "goal_created", target: 1 },
  },
  {
    id: "triple_threat",
    title: "Triple Threat",
    description: "Set 3 financial goals.",
    flavorText: "Short-term, medium-term, long-term. You've got a plan.",
    category: "goals",
    tier: "silver",
    points: 25,
    rarityTarget: 0.2,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "goal_created", target: 3 },
  },
  {
    id: "dream_realized",
    title: "Dream Realized",
    description: "Hit a financial goal.",
    flavorText: "The plan worked. On to the next one.",
    category: "goals",
    tier: "gold",
    points: 75,
    rarityTarget: 0.1,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "goal_hit", target: 1 },
  },
];
