import type { Achievement } from "../types";

export const HIDDEN: ReadonlyArray<Achievement> = [
  {
    id: "the_contrarian",
    title: "The Contrarian",
    description: "Remove something from your watchlist.",
    flavorText: "Sometimes the best trade is the one you don't make.",
    category: "hidden",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.3,
    isHidden: true,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "watchlist_removed", target: 1 },
  },
  {
    id: "share_the_wealth",
    title: "Share the Wealth",
    description: "Share one of your achievements.",
    flavorText: "The edge is only the edge if others don't have it. You shared anyway.",
    category: "social",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.15,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "achievement_shared", target: 1 },
  },
  {
    id: "the_completionist",
    title: "The Completionist",
    description: "Use every calculator at least once.",
    flavorText: "No tool left untouched. The full arsenal, deployed.",
    category: "meta",
    tier: "gold",
    points: 75,
    rarityTarget: 0.05,
    isHidden: true,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "distinct", event: "calculator_used", key: "kind", target: 7 },
  },
];
