import type { Achievement } from "../types";

export const NEWS: ReadonlyArray<Achievement> = [
  {
    id: "morning_brief",
    title: "Morning Brief",
    description: "Read 5 news articles.",
    flavorText: "The informed investor wakes up before the market does.",
    category: "news",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.6,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "news_read", target: 5 },
  },
  {
    id: "news_junkie",
    title: "News Junkie",
    description: "Read 25 news articles.",
    flavorText: "You read the tape before the tape reads you.",
    category: "news",
    tier: "silver",
    points: 25,
    rarityTarget: 0.3,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "news_read", target: 25 },
  },
  {
    id: "market_sentinel",
    title: "Market Sentinel",
    description: "Read 100 news articles.",
    flavorText: "Nothing moves the market without you noticing first.",
    category: "news",
    tier: "gold",
    points: 75,
    rarityTarget: 0.07,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "news_read", target: 100 },
  },
];
