import type { Achievement } from "../types";

export const ONBOARDING: ReadonlyArray<Achievement> = [
  {
    id: "welcome_to_the_terminal",
    title: "Welcome to the Terminal",
    description: "Create your FinHub account.",
    flavorText: "The bell has rung.",
    category: "onboarding",
    tier: "bronze",
    points: 10,
    rarityTarget: 1.0,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "account_created", target: 1 },
  },
  {
    id: "hello_wall_street",
    title: "Hello, Wall Street",
    description: "Research your first ticker.",
    flavorText: "Every empire starts with a single line item.",
    category: "onboarding",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.95,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "ticker_viewed", target: 1 },
  },
  {
    id: "the_architect",
    title: "The Architect",
    description: "Create your first portfolio.",
    flavorText: "Foundations matter.",
    category: "onboarding",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.7,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "portfolio_created", target: 1 },
  },
  {
    id: "the_watcher",
    title: "The Watcher",
    description: "Add your first watchlist item.",
    flavorText: "Patience is a position.",
    category: "onboarding",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.7,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "watchlist_added", target: 1 },
  },
  {
    id: "number_cruncher",
    title: "Number Cruncher",
    description: "Open your first calculator.",
    flavorText: "Math is the only honest broker.",
    category: "onboarding",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.6,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "calculator_used", target: 1 },
  },
  {
    id: "newsie",
    title: "Newsie",
    description: "Read your first news article.",
    flavorText: "Information has always been the edge.",
    category: "onboarding",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.7,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "news_read", target: 1 },
  },
  {
    id: "custom_built",
    title: "Custom Built",
    description: "Run your first custom screen.",
    flavorText: "Filters are how you find signal in the noise.",
    category: "onboarding",
    tier: "silver",
    points: 25,
    rarityTarget: 0.4,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "screen_run", target: 1 },
  },
];
