import type { Achievement } from "../types";

export const PORTFOLIO: ReadonlyArray<Achievement> = [
  {
    id: "first_holding",
    title: "First Position",
    description: "Add your first holding to a portfolio.",
    flavorText: "Every empire begins with a single line item.",
    category: "portfolio",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.75,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "holding_added", target: 1 },
  },
  {
    id: "well_diversified",
    title: "Well Diversified",
    description: "Add 5 holdings across your portfolios.",
    flavorText: "Don't put all your eggs in one basket.",
    category: "portfolio",
    tier: "silver",
    points: 25,
    rarityTarget: 0.45,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "holding_added", target: 5 },
  },
  {
    id: "portfolio_builder",
    title: "Portfolio Builder",
    description: "Add 15 holdings across your portfolios.",
    flavorText: "The portfolio is the strategy made visible.",
    category: "portfolio",
    tier: "gold",
    points: 75,
    rarityTarget: 0.12,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "holding_added", target: 15 },
  },
  {
    id: "dual_mandate",
    title: "Dual Mandate",
    description: "Create 2 separate portfolios.",
    flavorText: "One for growth. One for everything else.",
    category: "portfolio",
    tier: "silver",
    points: 25,
    rarityTarget: 0.3,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "portfolio_created", target: 2 },
  },
];
