import type { Achievement } from "../types";

export const RESEARCH: ReadonlyArray<Achievement> = [
  // Ticker research depth
  {
    id: "curious_mind",
    title: "Curious Mind",
    description: "Research 5 distinct tickers.",
    flavorText: "The first five are always the slowest.",
    category: "research",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.6,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "distinct", event: "ticker_viewed", key: "ticker", target: 5 },
  },
  {
    id: "market_analyst",
    title: "Market Analyst",
    description: "Research 10 distinct tickers.",
    flavorText: "Pattern recognition begins.",
    category: "research",
    tier: "silver",
    points: 25,
    rarityTarget: 0.35,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "distinct", event: "ticker_viewed", key: "ticker", target: 10 },
  },
  {
    id: "equity_explorer",
    title: "Equity Explorer",
    description: "Research 25 distinct tickers.",
    flavorText: "The market is wider than it looks.",
    category: "research",
    tier: "silver",
    points: 25,
    rarityTarget: 0.2,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "distinct", event: "ticker_viewed", key: "ticker", target: 25 },
  },
  {
    id: "wall_street_walker",
    title: "Wall Street Walker",
    description: "Research 50 distinct tickers.",
    flavorText: "You walk these halls now.",
    category: "research",
    tier: "gold",
    points: 75,
    rarityTarget: 0.08,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "distinct", event: "ticker_viewed", key: "ticker", target: 50 },
  },
  {
    id: "centurion",
    title: "Centurion",
    description: "Research 100 distinct tickers.",
    flavorText: "You have looked the Street in the eye one hundred times.",
    category: "research",
    tier: "platinum",
    points: 200,
    rarityTarget: 0.02,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "distinct", event: "ticker_viewed", key: "ticker", target: 100 },
  },
  // Deep dives
  {
    id: "deep_diver",
    title: "Deep Diver",
    description: "Open 5 deep dive reports.",
    flavorText: "The surface tells you the price. The depth tells you the value.",
    category: "research",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.4,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "deep_dive_opened", target: 5 },
  },
  {
    id: "earnings_hawk",
    title: "Earnings Hawk",
    description: "View earnings data on 5 tickers.",
    flavorText: "Guidance matters. You check every quarter.",
    category: "research",
    tier: "silver",
    points: 25,
    rarityTarget: 0.25,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "earnings_viewed", target: 5 },
  },
  {
    id: "chart_reader",
    title: "Chart Reader",
    description: "Open 10 advanced charts.",
    flavorText: "Price tells a story. You've learned to read it.",
    category: "research",
    tier: "silver",
    points: 25,
    rarityTarget: 0.2,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "advanced_chart_opened", target: 10 },
  },
  // Screeners
  {
    id: "screened_in",
    title: "Screened In",
    description: "Save a custom stock screen.",
    flavorText: "The filter is the thesis, made permanent.",
    category: "research",
    tier: "silver",
    points: 25,
    rarityTarget: 0.2,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "screen_saved", target: 1 },
  },
  {
    id: "filter_jockey",
    title: "Filter Jockey",
    description: "Run 10 stock screens.",
    flavorText: "Signal is scarce. You've learned how to find it.",
    category: "research",
    tier: "silver",
    points: 25,
    rarityTarget: 0.15,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "screen_run", target: 10 },
  },
  {
    id: "quantitative",
    title: "Quantitative",
    description: "Run 25 stock screens.",
    flavorText: "You don't guess at the market. You compute it.",
    category: "research",
    tier: "gold",
    points: 75,
    rarityTarget: 0.05,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "screen_run", target: 25 },
  },
  // Watchlist
  {
    id: "watchlist_curator",
    title: "Watchlist Curator",
    description: "Add 5 tickers to your watchlist.",
    flavorText: "A curated list is a curated mind.",
    category: "research",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.45,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "watchlist_added", target: 5 },
  },
  {
    id: "buy_list",
    title: "Buy List",
    description: "Add 15 tickers to your watchlist.",
    flavorText: "The watch list is the waiting list.",
    category: "research",
    tier: "silver",
    points: 25,
    rarityTarget: 0.2,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "count", event: "watchlist_added", target: 15 },
  },
];
