import type { Achievement } from "../types";

export const RESEARCH: ReadonlyArray<Achievement> = [
  {
    id: "curious_mind",
    title: "Curious Mind",
    description: "Research 5 distinct tickers.",
    flavorText: "The first five are always the slowest.",
    category: "research",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.6,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "distinct", event: "ticker_viewed", key: "ticker", target: 5 },
  },
  {
    id: "market_analyst",
    title: "Market Analyst",
    description: "Research 10 distinct tickers.",
    flavorText: "Pattern recognition begins.",
    category: "research",
    tier: "silver",
    points: 25,
    rarityTarget: 0.35,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "distinct", event: "ticker_viewed", key: "ticker", target: 10 },
  },
  {
    id: "equity_explorer",
    title: "Equity Explorer",
    description: "Research 25 distinct tickers.",
    flavorText: "The market is wider than it looks.",
    category: "research",
    tier: "silver",
    points: 25,
    rarityTarget: 0.2,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "distinct", event: "ticker_viewed", key: "ticker", target: 25 },
  },
  {
    id: "wall_street_walker",
    title: "Wall Street Walker",
    description: "Research 50 distinct tickers.",
    flavorText: "You walk these halls now.",
    category: "research",
    tier: "gold",
    points: 75,
    rarityTarget: 0.08,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "distinct", event: "ticker_viewed", key: "ticker", target: 50 },
  },
  {
    id: "centurion",
    title: "Centurion",
    description: "Research 100 distinct tickers.",
    flavorText: "You have looked the Street in the eye one hundred times.",
    category: "research",
    tier: "platinum",
    points: 200,
    rarityTarget: 0.02,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "distinct", event: "ticker_viewed", key: "ticker", target: 100 },
  },
];
