import type { Achievement } from "../types";

export const STREAKS: ReadonlyArray<Achievement> = [
  // Login streaks
  {
    id: "three_day_trader",
    title: "Three Day Trader",
    description: "Maintain a 3 day login streak.",
    flavorText: "Consistency is its own kind of conviction.",
    category: "streaks",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.5,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "login", target: 3 },
  },
  {
    id: "week_warrior",
    title: "Week Warrior",
    description: "Maintain a 7 day login streak.",
    flavorText: "A full trading week, plus the weekend.",
    category: "streaks",
    tier: "silver",
    points: 25,
    rarityTarget: 0.25,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "login", target: 7 },
  },
  {
    id: "fortnight_force",
    title: "Fortnight Force",
    description: "Maintain a 14 day login streak.",
    flavorText: "Two weeks of compounded attention.",
    category: "streaks",
    tier: "silver",
    points: 25,
    rarityTarget: 0.15,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "login", target: 14 },
  },
  {
    id: "monthly_maven",
    title: "Monthly Maven",
    description: "Maintain a 30 day login streak.",
    flavorText: "A full cycle. Earnings season looks different now.",
    category: "streaks",
    tier: "gold",
    points: 75,
    rarityTarget: 0.06,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "login", target: 30 },
  },
  {
    id: "sixty_day_strong",
    title: "Sixty Day Strong",
    description: "Maintain a 60 day login streak.",
    flavorText: "Two months without missing a beat.",
    category: "streaks",
    tier: "gold",
    points: 75,
    rarityTarget: 0.03,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "login", target: 60 },
  },
  {
    id: "centurion_streak",
    title: "Centurion",
    description: "Maintain a 100 day login streak.",
    flavorText: "One hundred days. The market respects no one who hasn't shown up this many times.",
    category: "streaks",
    tier: "platinum",
    points: 200,
    rarityTarget: 0.01,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "login", target: 100 },
  },
  {
    id: "full_year",
    title: "Full Year",
    description: "Maintain a 365 day login streak.",
    flavorText: "A full revolution around the sun. Not a single day missed.",
    category: "streaks",
    tier: "mythic",
    points: 500,
    rarityTarget: 0.002,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "login", target: 365 },
  },
  // News-read streaks
  {
    id: "daily_reader",
    title: "Daily Reader",
    description: "Read the news 3 days in a row.",
    flavorText: "The market speaks every day. You listened.",
    category: "streaks",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.35,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "news_read", target: 3 },
  },
  {
    id: "weekly_reader",
    title: "Weekly Reader",
    description: "Read the news 7 days in a row.",
    flavorText: "Seven days of signal over noise.",
    category: "streaks",
    tier: "silver",
    points: 25,
    rarityTarget: 0.12,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "news_read", target: 7 },
  },
];
