import type { Achievement } from "../types";

export const STREAKS: ReadonlyArray<Achievement> = [
  {
    id: "three_day_trader",
    title: "Three Day Trader",
    description: "Maintain a 3 day login streak.",
    flavorText: "Consistency is its own kind of conviction.",
    category: "streaks",
    tier: "bronze",
    points: 10,
    rarityTarget: 0.5,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "login", target: 3 },
  },
  {
    id: "week_warrior",
    title: "Week Warrior",
    description: "Maintain a 7 day login streak.",
    flavorText: "A full trading week, plus the weekend.",
    category: "streaks",
    tier: "silver",
    points: 25,
    rarityTarget: 0.25,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "login", target: 7 },
  },
  {
    id: "fortnight_force",
    title: "Fortnight Force",
    description: "Maintain a 14 day login streak.",
    flavorText: "Two weeks of compounded attention.",
    category: "streaks",
    tier: "silver",
    points: 25,
    rarityTarget: 0.15,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "login", target: 14 },
  },
  {
    id: "monthly_maven",
    title: "Monthly Maven",
    description: "Maintain a 30 day login streak.",
    flavorText: "A full cycle. Earnings season looks different now.",
    category: "streaks",
    tier: "gold",
    points: 75,
    rarityTarget: 0.06,
    isHidden: false,
    isSeasonal: false,
    enabled: true,
    requirement: { kind: "streak", streak: "login", target: 30 },
  },
];
